version: "3"

services:     
  dj:
    container_name: backend
    build: backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/code
    ports:
      - "8080:8080"
